development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:721b9adc8f03099cdd0a778754d60494@cod.redistogo.com:11216/
  # channel_prefix: mafia-server_production
